//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperScript.Templates.jQueryTmpl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperScript.Templates.jQueryTmpl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function (a) { var r = a.fn.domManip, d = &quot;_tmplitem&quot;, q = /^[^&lt;]*(&lt;[\w\W]+&gt;)[^&gt;]*$|\{\{\! /, b = {}, f = {}, e, p = { key: 0, data: {} }, i = 0, c = 0, l = []; function g(g, d, h, e) { var c = { data: e || (e === 0 || e === false) ? e : d ? d.data : {}, _wrap: d ? d._wrap : null, tmpl: null, parent: d || null, nodes: [], calls: u, nest: w, wrap: x, html: v, update: t }; g &amp;&amp; a.extend(c, g, { nodes: [], parent: d }); if (h) { c.tmpl = h; c._ctnt = c._ctnt || c.tmpl(a, c); c.key = ++i; (l.length ? f : b)[i] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery_tmpl {
            get {
                return ResourceManager.GetString("jquery_tmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Obtained from https://github.com/andrewdavey/cassette/blob/master/src/Cassette.JQueryTmpl/Resources/jqueryTmplCompiler.js
        ///
        ///// This code was butchered out of https://github.com/jquery/jquery-tmpl
        ///// It provides just enough to build HTML templates into a JavaScript function.
        ///
        ////*!
        ///* jQuery Templates Plugin 1.0.0pre
        ///* http://github.com/jquery/jquery-tmpl
        ///* Requires jQuery 1.4.2
        ///*
        ///* Copyright Software Freedom Conservancy, Inc.
        ///* Dual licensed under the MIT or GPL Version 2 licenses.
        ///* http://jquer [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jqueryTmplCompiler {
            get {
                return ResourceManager.GetString("jqueryTmplCompiler", resourceCulture);
            }
        }
    }
}
